run:
  concurrency: 4
  timeout: 2m
  tests: false

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100 # TODO: tune (was 100)
    statements: 50 # TODO: tune (was 50)
  gci:
    local-prefixes: github.com/Posrabi/flashy
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - whyNoLint
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/Posrabi/flashy
  golint:
    min-confidence: 0
  lll:
    line-length: 140 # TODO: tune (was 140)
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    # - funlen # TODO: re-enable
    - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo # TODO: re-enable
    - godot
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll # TODO: re-enable
    - nakedret
    # - noctx # TODO: re-enable
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
# Using --fix will automatically fix linting issues for you
# i.e. `golangci-lint run -v --no-config --disable-all -E whitespace --fix`
# Not ALL commands that can be run with --fix, here is a legal list:
# whitespace
# godot
