name: Go build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Install buf
        run: bash buf_install.sh

      - name: Build
        run: make code

      - name: Install cqlsh
        run: |
          pip3 install cqlsh
          cqlsh --version

      - name: Test
        run: bash test.sh
