name: React build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: cd frontend/flashy && yarn

      - name: Build
        run: cd frontend/Flashy && yarn build
